name: example
description: Example app to test the chat_widget package
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  chat_widget:
    path: ../

flutter:
  uses-material-design: true
